# golangci-lint configuration
# https://golangci-lint.run/usage/configuration/
version: "2"

run:
  timeout: 5m

linters:
  default: standard
  enable:
    - errcheck
  exclusions:
    # Exclude macOS-only menubar app (requires systray which needs GTK on Linux)
    paths:
      - cmd/cassh-menubar
